Добавляет разметку страниц сайта
htmlacademy-htmlcss/1745893-sedona-1 pull request #2
Opened 2023-10-06 09:26 UTC by SerialEditor

Добавляет разметку контента главной страницы сайта и страницы каталога

2023-10-06 19:55 UTC, SerialEditor commented
Поспешил с добавлением графики в проект, в последнем коммите она полностью удалена

2023-10-07 11:53 UTC, andreysgra requested changes
В целом разметка выполнена отлично.

2023-10-07 11:53 UTC, andreysgra commented on catalog.html
> +    <main class="main-inner">
`main` главной страницы ничем не отличается от `main` внутренних страниц, поэтому не стоит задавать отдельные классы `main-index` и `main-inner`. Лучше использовать один `main-container` для всех страниц.

2023-10-07 11:53 UTC, andreysgra commented on catalog.html
> +            </label>
Этот момент мы обсуждали на консультации: использовать в данном случае `input type="range"` не стоит. Ползунки размечаются кнопками, шкала с помощью `div`.

2023-10-07 11:53 UTC, andreysgra commented on catalog.html
> +          <button type="submit">Применить</button>
Не совсем понятен смысл перестановки местами кнопок.

2023-10-07 11:53 UTC, andreysgra commented on catalog.html
> +            <option value="cheap">Сначала дешевые</option>
Стоит добавить ещё опции, которые в макете не показаны: "Сначала дорогие", "Популярные" и т.д.

2023-10-07 11:53 UTC, andreysgra commented on catalog.html
> +            <img src="#" alt="Звёздное небо, вид из пещеры.">
Название гостиницы и её изображение стоит обернуть ссылкой (одна на оба элемента).

2023-10-09 17:43 UTC, merged