Декоративные элементы всех страниц
htmlacademy-htmlcss/1745893-sedona-1 pull request #8
Opened 2023-11-03 08:21 UTC by SerialEditor

2023-11-03 08:36 UTC, SerialEditor commented on images/icons/block-layout.svg
Проморгал удаление viewbox у векторных изображений при оптимизации SVGOMG - экспортировал заново; в нескольких редактировал код (добавил удалённый viewbox)

2023-11-03 08:36 UTC, SerialEditor commented on styles/styles.css
> +.site-navigation-link[href]:hover {
В макете нет описания пользовательского взаимодействия со ссылками в навигации (.site-navigation-link, user-navigation-link) - задал стили, старался попасть в тон макету

2023-11-04 07:39 UTC, andreysgra requested changes

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.button:focus {
Здесь, и для других интерактивных элементов, состояние фокуса лучше описывать через псевдо класс `:focus-visible`. Отличие этого псевдо класса от `:focus` в том, что браузер сам решает, нужно ли визуальное изменение на этом элементе в состоянии фокуса. Если для навигации используется клавиатура, то состояние фокуса отображается, если же мышь, то нет, так как пользователям использующим мышь неважно находится ли данный элемент в фокусе.

Визуальное различие при использовании мыши можно заметить таким образом: нажмите кнопку мыши на интерактивном элементе, где стили фокуса описаны через псевдо класс `:focus` и не отпуская кнопку уведите курсор за пределы области этого элемента, а затем отпустите кнопку. На этом элементе останется визуальное состояние фокуса. Если же описать все эти свойства в `:focus-visible`, то такого эффекта не будет (сам эффект на мой взгляд нежелателен).

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +}
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01): в этом [пункте](https://codeguide.academy/html-css.html#css-multiselectors) показан пример переноса селекторов.

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.breadcrumbs-link-homepage:hover path, .breadcrumbs-link-homepage:focus path {
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01)

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.add-favorites:hover, .add-favorites:focus {
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01)

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.added-favorites:hover, .added-favorites:focus {
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01)

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.pagination-show-more:hover, .pagination-show-more:focus {
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01)

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.footer-social-link:hover path, .footer-social-link:focus path {
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01)

2023-11-04 07:39 UTC, andreysgra commented on styles/styles.css
> +.htmlacademy-logo:hover path, .htmlacademy-logo:focus path {
[PROJ-01](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01)

2023-11-05 09:18 UTC, merged